name: Sleepy_Staging!
on:
  workflow_dispatch:

jobs:
  sleepybuild:
    runs-on: ubuntu-latest

    steps:
    - name: Creating Env!
      uses: actions/checkout@v2
      
    - name: Setting up Env!
      run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git make bc bison \
          openssl curl zip kmod cpio flex libelf-dev \
          libssl-dev libtfm-dev wget device-tree-compiler \
          ca-certificates python3 python2 binutils \
          binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi
    
    - name: Building Kernel..
      run: |
          cp sleepy_staging.sh mido && cd mido && chmod +x sleepy_staging.sh
          touch chatid
          touch botapi
          base64 -i chatid
          base64 -i botapi
          echo ${{ secrets.CHAT_ID }} | base64 -d > chatid
          echo ${{ secrets.BOT_API }} | base64 -d > botapi
          bash sleepy_staging.sh
      shell: bash
      env:
         CHATID: ${{ secrets.CHAT_ID }}
         API_BOT: ${{ secrets.BOT_API }}
